### PR TITLE
Adds vimlike bindings for easier text navigation

### PR DESCRIPTION
**Pull request by Beasta**

### CODE REVIEW

**Comment by Zettt** [comment]
@Beasta How do you intend users use this? I think I'm missing the point. Can you please explain? 

Thanks for the contribution!

**Comment by Beasta** [comment]
My favorite part about these shortcuts is being able to navigate anywhere that requires the arrow keys, without leaving the home row. A perfect example is drop down boxes. Often times you start typing in a drop down box and you want the second item in the dropdown. You don't want to have to lift your hand and put it on the arrow keys to select that item. With these VIM bindings, you can stay on your home row and still select that second item.

**Comment by Zettt** [comment]
That confuses me even more. With Full Keyboard Access this is really just `<spacebar> <arrow keys>`. Never understood why it's so complicated to move one's hands, but I guess not everyone has to use these keybindings anyway. They are a nice contribution. I'll check it out.

**Comment by Beasta** [comment]
I just recently found Karabiner which is a better solution for these vim bindings.

**Comment by Zettt** [comment]
Probably, yes. I'll close this pull request.

**Comment by Zettt** [comment]
@Beasta I had some time to check out the pull request you sent. Sadly your changes are incompatible with the way how I handle this repository. You submitted a Keyboard Maestro library file. The readme page clearly says what to do under [Participate](https://github.com/Zettt/km-macros#participate). I'm deleting the files now, but leave them in the commit history. If you still want them added please submit a new pull request with individual files. In this case, it's better to keep them in a "Vim" group in Keyboard Maestro.

**Pull request closed without merging**
